[package]
name = "haussmann"
authors = ["Antonin Hérault <antonherault@gmail.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
haussmann-graphics = { path = "graphics/" }
haussmann-widgets = { path = "widgets/" }
